[package]
name = "base"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
bincode = "1.3.3"
log = "0.4.22"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
macro = { path = "../macro" }
clap = { version = "4.6.6", features = ["derive"] }
winit = { version = "=0.29.15", features = ["android-native-activity", "rwh_05"] }
raw-window-handle = "=0.5.2"
mlua = { version = "0.12.1", features = ["luajit52", "send", "vendored"] }
wincode = { version = "0.6.1", features = ["derive"] }
bitflags = "2.13.2"
ash = "0.38.0"
ash-window = "0.13.0"
naga = { version = "30.0.1", features = ["glsl-in", "spv-out", "wgsl-in"] }
glyph_brush = { version = "0.7", default-features = false }
zstd = "0.14.0"
memmap2 = "0.9.11"
gilrs = "0.11.2"

[build-dependencies]
cc = "1"
mlua = { version = "0.12.1", features = ["luajit52", "vendored"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(not(target_os = "ios"))'.dependencies]
glutin = "=0.31.3"
glutin-winit = "=0.4.2"
glow = "=0.12.3"
glow_glyph = "0.6.0"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
metal = "0.29"
objc = "0.2"
glyph_brush = "0.7"
core-graphics-types = "0.1.3"

[target.'cfg(windows)'.dependencies]
glyph_brush = "0.7"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Threading",
] }

[features]
default = ["client", "server"]
client = []
server = []

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
